Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/IfElse_1.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hi
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/IfElse_1.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hello
Hi There...
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/IfElse_1.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : HELLO
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/IfElse_1.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : HeLLo
Hi There...
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/IfElse_1.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hi
I don't understand
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_2.py 
Enter your name : Ravu
Welcome Ravu
Enter your message : hello
Hi There...
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_2.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hello
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...
Hi There...Traceback (most recent call last):
  File "C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_2.py", line 10, in <module>
    print("Hi There...")
KeyboardInterrupt
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_2.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hi
I don't understand
Enter your message : hello
Hi There...
Enter your message : bye
Bye Ravi Have a nice day...
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_3.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hi
Hi There...
Enter your message : hey
Hi There...
Enter your message : hello
Hi There...
Enter your message : bye
Bye Ravi Have a nice day...
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_4.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hi
Hi There...
Enter your message : hey
Hi There...
Enter your message : hello
Hi There...
Enter your message : bye
Bye Ravi Have a nice day...
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_5.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hi
Hi There...
Enter your message : hello
Hi There...
Enter your message : date
16/08/19,Fri
Enter your message : time
11/17/27,AM
Enter your message : date please
16/08/19,Fri
Enter your message : tell me date
16/08/19,Fri
Enter your message : bye
Bye Ravi Have a nice day...
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_5.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : hi
Hi There...
Enter your message : play music
Playing => Dub Theri Step with Lyrics   Theri   Vijay, Samantha, Amy Jackson   Atlee   G.V.Prakash Kumar.ogg
Enter your message : bye
Bye Ravi Have a nice day...
>>> import glob
>>> glob.glob('*.mp3')
['5-Varlaam Varlaam Vaa-SenSongsMp3.Co.mp3', 'BIGGEST BASS DROP EVER! (EXTREME BASS TEST!!!).mp3', 'Billian-Billian-Guri.mp3', 'Cristiano Ronaldo - Faded Best Moments 2017 • 100.000 Subscribers.mp3', 'Ek Pal Ka Jeena-(Mr-Jatt.com).mp3', 'Na Ja.mp3', 'Shape of You.mp3', 'StreetFighter.mp3']
>>> import easygui
>>> easygui.fileopenbox()
'C:\\Users\\asus\\Music\\Cristiano Ronaldo - Faded Best Moments 2017 • 100.000 Subscribers.mp3'
>>> 
 RESTART: C:/Users/asus/Documents/Data/DataTransfer/BMPL_Batches/2019/Aug/PythonMorningReg/ifElse_5.py 
Enter your name : Ravi
Welcome Ravi
Enter your message : play music
Playing => Kaththi Theme…The Sword of Destiny - Full Audio.ogg
Enter your message : play music
Playing => Billian-Billian-Guri.mp3
Enter your message : play music
Playing => Ek Pal Ka Jeena-(Mr-Jatt.com).mp3
Enter your message : play music
Playing => Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
Enter your message : bye
Bye Ravi Have a nice day...
>>> for song in songs:
	print(song)

	
5-Varlaam Varlaam Vaa-SenSongsMp3.Co.mp3
BIGGEST BASS DROP EVER! (EXTREME BASS TEST!!!).mp3
Billian-Billian-Guri.mp3
Cristiano Ronaldo - Faded Best Moments 2017 • 100.000 Subscribers.mp3
desktop.ini
Dub Theri Step with Lyrics   Theri   Vijay, Samantha, Amy Jackson   Atlee   G.V.Prakash Kumar.ogg
Ek Pal Ka Jeena-(Mr-Jatt.com).mp3
Kaththi Theme…The Sword of Destiny - Full Audio.ogg
music_1.ogg
Na Ja.mp3
Shape of You.mp3
Street Fighter V Soundtrack - Main Menu.ogg
Street Fighter V Soundtrack - Ryu's Theme.ogg
StreetFighter.mp3
Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
>>> for i in range(len(songs)):
	print(i,song)

	
0 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
1 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
2 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
3 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
4 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
5 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
6 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
7 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
8 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
9 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
10 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
11 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
12 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
13 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
14 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
>>> for i in range(len(songs)):
	print(i,songs[i])

	
0 5-Varlaam Varlaam Vaa-SenSongsMp3.Co.mp3
1 BIGGEST BASS DROP EVER! (EXTREME BASS TEST!!!).mp3
2 Billian-Billian-Guri.mp3
3 Cristiano Ronaldo - Faded Best Moments 2017 • 100.000 Subscribers.mp3
4 desktop.ini
5 Dub Theri Step with Lyrics   Theri   Vijay, Samantha, Amy Jackson   Atlee   G.V.Prakash Kumar.ogg
6 Ek Pal Ka Jeena-(Mr-Jatt.com).mp3
7 Kaththi Theme…The Sword of Destiny - Full Audio.ogg
8 music_1.ogg
9 Na Ja.mp3
10 Shape of You.mp3
11 Street Fighter V Soundtrack - Main Menu.ogg
12 Street Fighter V Soundtrack - Ryu's Theme.ogg
13 StreetFighter.mp3
14 Vedalam - The Theri Theme Lyric   Ajith Kumar, Shruti Haasan   Anirudh.ogg
>>> index = int(input("Enter the track number : "))
Enter the track number : 5
>>> os.startfile(songs[index])
>>> import webbrowser
>>> webbrowser.open("google.com")
True
>>> msg = "open facebook"
>>> msg.split()
['open', 'facebook']
>>> msg.split()[1]
'facebook'
>>> web = msg.split()[1]
>>> webbrowser.open
<function open at 0x0000015FF0CAF510>
(
>>> webbrowser.open(web+'.com')
True
>>> msg.split()[-1]
'facebook'
>>> stopwords = ["can","you","please","the","what","what's"]
>>> msg = "can you please open facebook"
>>> text = []
>>> for word in msg.split():
	if word not in stopwords:
		text.append(word)

		
>>> text
['open', 'facebook']
>>> msg.split()
['can', 'you', 'please', 'open', 'facebook']
>>> 
